name: Letterink -- home page
favicon: null
layout_spectrum: 0.66803
typography_spectrum: 0.74227
title: Letterink
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefaee'
    - '#42403a'
    - '#f89c67'
    - '#827f76'
    - '#88c2d5'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
