name: Letterink -- home page
favicon: null
layout_spectrum: 0.66803
typography_spectrum: 0.74227
title: Letterink
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#47f3f7'
    - '#410409'
    - '#fb8815'
    - '#fceb22'
    - '#e30363'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
