name: Letterink -- home page
favicon: null
layout_spectrum: 0.75926
typography_spectrum: 0.43871
title: Letterink
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e1d4'
    - '#e5752b'
    - '#cd3b6f'
    - '#bbb5a9'
    - '#928a7d'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
