name: Letterink -- home page
favicon: null
layout_spectrum: 0.6855379040353
typography_spectrum: 0.9762034465093166
title: Letterink -- Streamline Lettering and digital calligraphy creation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22592616803012788
  lightness: 0.5381610663607717
  saturation: 0.622625739313662
  rhythmicContrast: 0.2785311653278768
purpose: []
